# DLP YT config
# https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#configuration

--js-runtimes bun # update flake.nix if you change it
--cookies-from-browser chrome
--wait-for-video 60-120
--live-from-start
--fragment-retries infinite
--retry-sleep 5
--hls-use-mpegts

-o ./output/%(title)s.%(ext)s
